version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - gh-packages
    schedule:
      interval: weekly
    versioning-strategy: increase
    allow:
      - dependency-name: '@typeform*'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependabot'
    groups:
      typeform:
        patterns:
          - '@typeform*'
    cooldown:
      default-days: 7
      exclude:
        - '@typeform/*'
    ignore:
      - dependency-name: semantic-release
        versions:
          - '>=25.0.0'
registries:
  gh-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.JENKINS_PAT_TOKEN }}
